language: php

dist: xenial

php:
    - "5.6"
    - "7.0"
    - "7.1"
    - "7.2"
    - "7.3"

before_script:
    - composer install --no-interaction

script:
    - make test-coverage
    - make check-style

after_success:
    - bash <(curl -s https://codecov.io/bash)
